### ISSUE TITLE
Problems I met & record for solution

### ISSUE THREAD

**Issue by GromShine** [hkair/Basketball-Action-Recognition#4]
Belowing is some problems I met and trying to solve to help me run the code

Dear author,
     I download your repo and find always bugs, and don't know how to start at first, bellowing is the record of my attempts

1. I download yolo3.cfg & yolo3.weights in main folder
2. I download the dataset.zip in https://github.com/simonefrancia/SpaceJam and unzip it into main folder.
3. I run the main.py, and selecting a rectangle and then it told me _'[Errno 2] No such file or directory: 'model_checkpoints/r2plus1d_augmented-2/r2plus1d_multiclass_19_0.0001.pt''_
4. and I think maybe I should run train.py at first to get the above 'r2plus1d_multiclass', but it told me _[Errno 2] No such file or directory: 'dataset/augmented_annotation_dict.json'_
5. and I think maybe I should run augment_video.py at first to get 'augmented_annotation_dict.json', but it told me 
_Traceback (most recent call last):_

  _File "D:\Basketball-Action-Recognition\augment_videos.py", line 128, in <module>_
    _augmentVideo(annotation_dict, labels_dict)_

  _File "D:\Basketball-Action-Recognition\augment_videos.py", line 23, in augmentVideo_
    _labels_dict = json.load(f, object_hook=keystoint)_

  _File "D:\anaconda3\envs\pymarl\lib\json\__init__.py", line 296, in load_
    _parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)_

  _File "D:\anaconda3\envs\pymarl\lib\json\__init__.py", line 361, in loads_
   _return cls(**kw).decode(s)_

  _File "D:\anaconda3\envs\pymarl\lib\json\decoder.py", line 337, in decode_
    _obj, end = self.raw_decode(s, idx=_w(s, 0).end())_

  _File "D:\anaconda3\envs\pymarl\lib\json\decoder.py", line 353, in raw_decode_
    _obj, end = self.scan_once(s, idx)_

_JSONDecodeError: Expecting property name enclosed in double quotes_

after above,
1. I modify the dataset\labels_dict.json to make sure the key is double quotes and I get the 'augmented_annotation_dict.json'
2. Then I run the train.py, it seems will train abt 1 hour, I ll update then
    it seems 1 epoch 1 hour, 25 epoch... seems I ll update tomorrow...
    after 1 epoch, I have 'model_checkpoints/r2plus1d_augmented-2/r2plus1d_multiclass_1_0.0001.pt', seems different from the above 'model_checkpoints/r2plus1d_augmented-2/r2plus1d_multiclass_19_0.0001.pt', maybe I should wait it 19 epoch
    ★attention, you should reserve 341M*25 ≈ 8.3G space to save them
3. now I have r2plus1d_multiclass_1_0.0001.pt~r2plus1d_multiclass_1_0.0024.pt, and it told me 
_Training complete in 1466m 17s_
_Best val Acc: 0.854709_
_Best Validation Loss:  0.45085233312969436 Epoch:  3_
_Best Training Loss:  0.022664556910204244 Epoch:  23_
_Traceback (most recent call last):_
_File "D:\Basketball-Action-Recognition\train.py", line 343, in <module>_
    _plot_epoch_

  _File "D:\Basketball-Action-Recognition\utils\checkpoints.py", line 88, in plot_curves_
    _plt.plot(epochs, train_acc, label='train accuracy')_

  _File "D:\anaconda3\envs\pymarl\lib\site-packages\matplotlib\pyplot.py", line 2759, in plot_
    _**({"data": data} if data is not None else {}), **kwargs)_

 _ File "D:\anaconda3\envs\pymarl\lib\site-packages\matplotlib\axes\_axes.py", line 1632, in plot_
    _lines = [*self._get_lines(*args, data=data, **kwargs)]_

  _File "D:\anaconda3\envs\pymarl\lib\site-packages\matplotlib\axes\_base.py", line 312, in __call__
    _yield from self._plot_args(this, kwargs)_

 _ File "D:\anaconda3\envs\pymarl\lib\site-packages\matplotlib\axes\_base.py", line 488, in _plot_args_
    _y = _check_1d(xy[1])_

  _File "D:\anaconda3\envs\pymarl\lib\site-packages\matplotlib\cbook\__init__.py", line 1304, in _check_1d_
    _return np.atleast_1d(x)_

  _File "<__array_function__ internals>", line 6, in atleast_1d_

  _File "D:\anaconda3\envs\pymarl\lib\site-packages\numpy\core\shape_base.py", line 65, in atleast_1d_
    _ary = asanyarray(ary)_

  _File "D:\anaconda3\envs\pymarl\lib\site-packages\torch\_tensor.py", line 678, in __array___
    _return self.numpy()_

_TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first._

4. I create 'output_videos' folder in main folder, then I run main.py and select some rectangle, I get an output  video as a result
5. ★so now if I want to have everyone's action recognition, I need to rectangle them one by one

**Comment by heqingdong** [comment]
Dear sir, I have suffered the same process as you posted. I put my test mp4 video in videos folder. But after I run main.py, I got an mp4 file that cannot be opened. How to get the correct result?
